# Переименовываем изображения в соответствии с нужными именами
Rename-Item -Path "images/12.jpg" -NewName "hero-bg.jpg"
Rename-Item -Path "images/11.jpg" -NewName "tour1.jpg"
Rename-Item -Path "images/9.jpg" -NewName "tour2.jpg"
Rename-Item -Path "images/8.jpg" -NewName "tour3.jpg"
Rename-Item -Path "images/7.jpg" -NewName "tours-hero.jpg"
Rename-Item -Path "images/6.jpg" -NewName "guide1.jpg"
Rename-Item -Path "images/5.jpg" -NewName "guide2.jpg"
Rename-Item -Path "images/4.jpg" -NewName "guide3.jpg"
Rename-Item -Path "images/3.jpeg" -NewName "gallery1.jpg"
Rename-Item -Path "images/2.jpeg" -NewName "gallery2.jpg"
Rename-Item -Path "images/image-asset.jpeg" -NewName "gallery3.jpg"
Rename-Item -Path "images/ruth_flunn.jpg" -NewName "gallery4.jpg"
Rename-Item -Path "images/flynn.png" -NewName "gallery5.jpg"
Rename-Item -Path "images/bruner.png" -NewName "gallery6.jpg" 